### ISSUE TITLE
error on get_total()

### ISSUE THREAD

**Issue by catafest** [mirumee/satchless#156]
I try this simple example and I got this error:
```
>>> import prices
>>> from satchless.item import Item
>>> from satchless.cart import Cart
>>> class my_product(Item):
...     def __repr__(self): return 'my_product()'
...     def get_price_per_item(self): return prices.Price(12, currency='EUR')
... 
>>> my_cart = Cart()
>>> my_product_001 = my_product()
>>> my_cart.add(my_product_001, quantity=3, data=['extra option 001'])
>>> my_cart.add(my_product_001, data=['extra option 002'])
>>> my_cart.add(my_product_001, data=['extra option 003'])
>>> list(my_cart)
[CartLine(product=my_product(), quantity=3, data=['extra option 001']), CartLine(product=my_product(), quantity=1, data=['extra option 002']), CartLine(product=my_product(), quantity=1, data=['extra option 003'])]
>>> my_cart.get_total()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mythcat/.local/lib/python3.7/site-packages/satchless/item/__init__.py", line 58, in get_total
    subtotals = [self.get_subtotal(item, **kwargs) for item in self]
  File "/home/mythcat/.local/lib/python3.7/site-packages/satchless/item/__init__.py", line 58, in <listcomp>
    subtotals = [self.get_subtotal(item, **kwargs) for item in self]
  File "/home/mythcat/.local/lib/python3.7/site-packages/satchless/item/__init__.py", line 55, in get_subtotal
    return item.get_total(**kwargs)
  File "/home/mythcat/.local/lib/python3.7/site-packages/satchless/item/__init__.py", line 84, in get_total
    return self.get_price_per_item(**kwargs) * self.get_quantity(**kwargs)
  File "/home/mythcat/.local/lib/python3.7/site-packages/satchless/cart/__init__.py", line 38, in get_price_per_item
    return self.product.get_price(**kwargs)
  File "/home/mythcat/.local/lib/python3.7/site-packages/satchless/item/__init__.py", line 96, in get_price
    return self.get_price_per_item(**kwargs)
  File "<stdin>", line 3, in get_price_per_item
AttributeError: module 'prices' has no attribute 'Price'
```

**Comment by NyanKiyoshi** [comment]
@catafest this is not `Price` to use but `Money`
